### PR TITLE
pdal 2.5.3

### PR DESCRIPTION
**Pull request by skupr-anaconda**
Changelog: https://github.com/PDAL/PDAL/blob/2.5.3/RELEASENOTES.txt
License: https://github.com/PDAL/PDAL/blob/2.5.3/LICENSE.txt
Requirements:
- https://github.com/PDAL/PDAL/blob/2.5.3/CMakeLists.txt
- https://github.com/PDAL/PDAL/tree/2.5.3/cmake

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
An error on linux:
`"  ERROR (pdal,lib/libpdal_plugin_reader_e57.so.15.3.0): .. but ['xerces-c'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)", "  ERROR (pdal,lib/libpdal_base.so.15.3.0): .. but ['libcurl'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)", "  ERROR (pdal,lib/libpdal_plugin_filter_trajectory.so.15.3.0): .. but ['glog'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)", "  ERROR (pdal,lib/libpdal_plugin_filter_trajectory.so.15.3.0): .. but ['gflags'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)", "  ERROR (pdal,lib/libpdal_plugin_writer_e57.so.15.3.0): .. but ['xerces-c'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)"]`

**Comment by skupr-anaconda** [comment]
An error on `win64`:
```
CMake Error at cmake/macros.cmake:139 (add_library):
  Target "libpdal_plugin_filter_trajectory" links to target
  "SuiteSparse::CHOLMOD" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?

Call Stack (most recent call first):
  plugins/trajectory/CMakeLists.txt:4 (PDAL_ADD_PLUGIN)

CMake Error at cmake/macros.cmake:139 (add_library):
  Target "libpdal_plugin_filter_trajectory" links to target
  "SuiteSparse::SPQR" but the target was not found.  Perhaps a find_package()
  call is missing for an IMPORTED target, or an ALIAS target is missing?
```
Looks like something is wrong with `suitesparse` and/or `ceres-solver` packages. It can happen because of `suitesparse` has been built with **static** libraries and not shared.

**Comment by skupr-anaconda** [comment]
I suspect that our `suitesparse` package is **outdated** and hasn't required functionality for `ceres-solver` and `pdal` on `win `https://github.com/AnacondaRecipes/suitesparse-feedstock/blob/445b48e7e6268895d0db0c33ced9f3da578ecff9/recipe/meta.yaml#L8-L10

**Comment by skupr-anaconda** [comment]
Required packages:
 * GDAL (required version >= 3.0)
   * Provides general purpose raster, vector, and reference system support
 * GeoTIFF
 * LibLZMA
   *  General compression support
 * CURL
 * Ceres
 * ZLIB
   * Compression support in BPF
   * Compression support in BPF
 * Draco (required version >= 1.5.6)
 * HDF5
 * PostgreSQL
 * XercesC
 * Threads, The thread library of the system
 * 
Optional packages:
 * ZSTD
   * General compression support
 * PkgConfig
 * LibXml2
 * OpenSSL (required version >= 1.1)
 * Eigen3 (required version >= 3.3.7)
 * glog (required version >= 0.5.0)
 * gflags (required version >= 2.2.2)

**Comment by skupr-anaconda** [comment]
We need ceres-solver with enabled shared libraries on win64 https://github.com/AnacondaRecipes/ceres-solver-feedstock/pull/2/

**Review by ELundby45 — APPROVED** [review]

**Review by akabanovs — APPROVED** [review]
LGTM

**Pull request merged**
